/* eslint-disable max-len */
export const PROJECTS_LINKS_CONSTANTS = {
  EVO_LANDING: 'https://evoplay-landong-spunch-agency.vercel.app/',
  LR_WEB: 'https://lonely-rabbit-spunch-agency.vercel.app/',
  SPUNCH_WEB: 'https://spunch.agency',
  IXNOME_LANDING: 'https://ixnome.com',
  IXNOME_APP: 'https://app.ixnome.com/sign-in',
  CAFE_DEMO: 'https://masha-girya.github.io/codempire-cafe/',
  CAFE_GITHUB: 'https://github.com/masha-girya/codempire-cafe',
  PHONE_DEMO: 'https://fe-sep22-fulfilled.github.io/frontend/#/',
  PHONE_GITHUB: 'https://github.com/FE-SEP22-FulFilled/frontend',
  CHUCK_DEMO: 'https://masha-girya.github.io/chuck-norris-jokes/',
  CHUCK_GITHUB: 'https://github.com/masha-girya/chuck-norris-jokes',
  TODO_DEMO: 'https://masha-girya.github.io/todo-application/',
  TODO_GITHUB: 'https://github.com/masha-girya/todo-application',
  BIKE_DEMO: 'https://masha-girya.github.io/bike-landing/',
  BIKE_GITHUB: 'https://github.com/masha-girya/bike-landing',
  RECIPES_WEB: 'https://thats-what-she-baked.vercel.app/',
  TODO_DRAG_DEMO: 'https://masha-girya.github.io/incode-test/',
  TODO_DRAG_GIHUB: 'https://github.com/masha-girya/incode-test',
  QUIZ_DEMO: 'https://masha-girya.github.io/quiz-test/#/quiz/1',
  QUIZ_GITHUB: 'https://github.com/masha-girya/quiz-test',
  PORTFOLIO: 'https://masha-girya.github.io/portfolio',
  CV: 'https://drive.google.com/file/d/1IhTa-_ESST9T4BISmK8Z48nJtCSXBUY6/view?usp=sharing',
} as const;
