export const TECHNOLOGIES_CONSTANTS = {
  CAFE: [
    'Nest.js',
    'React',
    'MUI',
    'TypeORM',
    'PostgreSQL',
    'Web3.js',
    'MetaMask',
    'Typescript',
    'Sass',
    'HTML',
    'GIT',
  ],
  PHONES: [
    'Node.js',
    'Express',
    'Typescript',
    'REST API',
    'React',
    'Sass',
    'HTML',
    'GIT',
  ],
  CHUCK: [
    'React',
    'Typescript',
    'Sass',
    'HTML',
    'Jest',
    'React Testing Lib',
    'BEM',
  ],
  TODO: ['React', 'Sass', 'HTML', 'REST API', 'React Transitions', 'BEM'],
  BIKE: ['Sass', 'HTML', 'BEM'],
} as const;
